### ISSUE TITLE
[BUG] Can't open actor menu [0.8.7]

### ISSUE THREAD

**Issue by Nopants** [CDeenen/SharedVision#6]
**Setup**
 - OS: Windows
 - Browser: Chrome, Foundry app
 - Module version: 1.0.4
 - Foundry version: 0.8.7
 - Gaming system & version: Shadowrun 5th Edition 0.7.17
 - Any other modules enabled: yes

**Describe the bug**
When trying to open the "Shared Vision" menu after doing it for the first time per actor, it doesn't show the dialog again. Wiping the modules flags from the actors .json makes the dialog show again one time.

**Console Log**
![image](https://user-images.githubusercontent.com/886406/122677417-6e672680-d1e2-11eb-9cc7-2ce0e39ca3ff.png)

**Comment by CDeenen** [comment]
Thanks for the bug report.
This has been fixed in v1.0.5. The problem was that for some reason Shadowrun automatically appears to convert array flags to objects, 5e and other systems I tested don't do that.
I added some code to check if the flag is an object, which then converts it into an array, so it should work now.
